### ISSUE TITLE
感谢师兄无私风险，现在官方有了latex模板了

### ISSUE THREAD

**Issue by 578223592** [lusccc/cqupt-thesis#2]

**Comment by shuaizujiaofu** [comment]
> _No description provided._

只找到本科毕设的模板呀，有没有研究生的

**Comment by 578223592** [comment]
> 只找到本科毕设的模板呀，有没有研究生的

有的，我就是研究生，你在网站上再找找，可能是研究生网站之类的。

**Comment by shuaizujiaofu** [comment]
谢谢老哥，找到了，网站是https://yjs.cqupt.edu.cn/info/1198/6904.htm
